const admin = require('firebase-admin');
const OpenAI = require('openai');
const ContentFilter = require('../utils/ContentFilter');
const QuestionValidator = require('../utils/QuestionValidator');

class QuestionService {
  constructor() {
    this.db = admin.firestore();
    this.openai = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY
    });
  }

  /**
   * Get questions for app consumption
   */
  async getQuestions({ category, difficulty, ageRange, includeImages, limit }) {
    try {
      let query = this.db.collection('questions')
        .where('isActive', '==', true)
        .where('status', '==', 'approved');

      if (category) {
        query = query.where('category', '==', category);
      }

      if (difficulty) {
        query = query.where('difficulty', '==', difficulty);
      }

      if (ageRange) {
        query = query.where('ageMin', '<=', ageRange.max)
                    .where('ageMax', '>=', ageRange.min);
      }

      if (includeImages) {
        query = query.where('hasImage', '==', true);
      }

      const snapshot = await query.limit(limit).get();
      const questions = [];

      snapshot.forEach(doc => {
        const data = doc.data();
        questions.push({
          id: doc.id,
          ...data,
          // Remove sensitive fields for app consumption
          reviewNotes: undefined,
          createdBy: undefined,
          lastModifiedBy: undefined
        });
      });

      return questions;
    } catch (error) {
      console.error('Error fetching questions:', error);
      throw new Error('Failed to fetch questions from database');
    }
  }

  /**
   * Generate new questions using AI
   */
  async generateQuestions({ category, difficulty, ageRange, count, useAI, reviewRequired }) {
    try {
      const questions = [];
      const batch = this.db.batch();

      for (let i = 0; i < count; i++) {
        let question;
        
        if (useAI) {
          question = await this.generateAIQuestion(category, difficulty, ageRange);
        } else {
          question = this.generateMockQuestion(category, difficulty, ageRange);
        }

        // Validate and filter content
        const validation = await QuestionValidator.validate(question);
        if (!validation.isValid) {
          console.warn(`Question validation failed: ${validation.errors.join(', ')}`);
          continue;
        }

        const filteredQuestion = await ContentFilter.filterForChildren(question, ageRange.min);

        // Create question document
        const questionRef = this.db.collection('questions').doc();
        const questionData = {
          ...filteredQuestion,
          category,
          difficulty,
          ageMin: ageRange.min,
          ageMax: ageRange.max,
          status: reviewRequired ? 'pending_review' : 'approved',
          isActive: true,
          createdAt: admin.firestore.FieldValue.serverTimestamp(),
          updatedAt: admin.firestore.FieldValue.serverTimestamp(),
          createdBy: 'system',
          usageCount: 0,
          reviewNotes: reviewRequired ? 'Generated by AI - pending review' : null
        };

        batch.set(questionRef, questionData);
        questions.push({ id: questionRef.id, ...questionData });
      }

      await batch.commit();

      return {
        questions,
        count: questions.length,
        status: reviewRequired ? 'pending_review' : 'approved'
      };
    } catch (error) {
      console.error('Error generating questions:', error);
      throw new Error('Failed to generate questions');
    }
  }

  /**
   * Generate AI question using OpenAI
   */
  async generateAIQuestion(category, difficulty, ageRange) {
    try {
      const prompt = this.createAIPrompt(category, difficulty, ageRange);
      
      const response = await this.openai.chat.completions.create({
        model: 'gpt-3.5-turbo',
        messages: [
          {
            role: 'system',
            content: 'You are an educational content creator specializing in age-appropriate quiz questions for children.'
          },
          {
            role: 'user',
            content: prompt
          }
        ],
        max_tokens: 1000,
        temperature: 0.7
      });

      const content = response.choices[0].message.content;
      return this.parseAIResponse(content);
    } catch (error) {
      console.error('AI generation failed:', error);
      // Fallback to mock question
      return this.generateMockQuestion(category, difficulty, ageRange);
    }
  }

  /**
   * Create AI prompt for question generation
   */
  createAIPrompt(category, difficulty, ageRange) {
    const difficultyText = difficulty.charAt(0).toUpperCase() + difficulty.slice(1);
    const ageText = `ages ${ageRange.min}-${ageRange.max}`;
    
    return `Create 1 educational quiz question about ${category} for children ${ageText} at ${difficultyText} level.

IMPORTANT: Return ONLY the question in this exact JSON format:
{
  "text": "Question text here?",
  "options": ["Option A", "Option B", "Option C", "Option D"],
  "correctAnswer": 0,
  "explanation": "Explanation of the correct answer",
  "tags": ["tag1", "tag2", "tag3"]
}

Make sure the question is:
- Age-appropriate for ${ageText}
- Educational and engaging
- Clear and unambiguous
- Safe for children
- Relevant to ${category} at ${difficultyText} level`;
  }

  /**
   * Parse AI response into question object
   */
  parseAIResponse(content) {
    try {
      // Extract JSON from response
      const jsonMatch = content.match(/\{[\s\S]*\}/);
      if (!jsonMatch) {
        throw new Error('No JSON found in AI response');
      }

      const questionData = JSON.parse(jsonMatch[0]);
      
      return {
        text: questionData.text,
        options: questionData.options,
        correctAnswer: questionData.correctAnswer,
        explanation: questionData.explanation,
        tags: questionData.tags || [],
        hasImage: false,
        imagePath: null,
        imagePrompt: null
      };
    } catch (error) {
      console.error('Error parsing AI response:', error);
      throw new Error('Failed to parse AI response');
    }
  }

  /**
   * Generate mock question as fallback
   */
  generateMockQuestion(category, difficulty, ageRange) {
    const mockQuestions = {
      math: [
        {
          text: "What is 5 + 3?",
          options: ["6", "7", "8", "9"],
          correctAnswer: 2,
          explanation: "5 + 3 equals 8.",
          tags: ["addition", "arithmetic", "numbers"]
        }
      ],
      science: [
        {
          text: "What do plants need to grow?",
          options: ["Water only", "Sunlight only", "Water and sunlight", "Nothing"],
          correctAnswer: 2,
          explanation: "Plants need both water and sunlight to grow.",
          tags: ["plants", "nature", "growth"]
        }
      ]
    };

    const categoryQuestions = mockQuestions[category] || mockQuestions.math;
    const randomQuestion = categoryQuestions[Math.floor(Math.random() * categoryQuestions.length)];
    
    return {
      ...randomQuestion,
      hasImage: false,
      imagePath: null,
      imagePrompt: null
    };
  }

  /**
   * Update question
   */
  async updateQuestion(id, updates) {
    try {
      const questionRef = this.db.collection('questions').doc(id);
      const updateData = {
        ...updates,
        updatedAt: admin.firestore.FieldValue.serverTimestamp(),
        lastModifiedBy: 'admin'
      };

      await questionRef.update(updateData);
      
      const updatedDoc = await questionRef.get();
      return { id: updatedDoc.id, ...updatedDoc.data() };
    } catch (error) {
      console.error('Error updating question:', error);
      throw new Error('Failed to update question');
    }
  }

  /**
   * Delete question
   */
  async deleteQuestion(id, permanent = false) {
    try {
      const questionRef = this.db.collection('questions').doc(id);
      
      if (permanent) {
        await questionRef.delete();
      } else {
        await questionRef.update({
          isActive: false,
          updatedAt: admin.firestore.FieldValue.serverTimestamp(),
          lastModifiedBy: 'admin'
        });
      }
    } catch (error) {
      console.error('Error deleting question:', error);
      throw new Error('Failed to delete question');
    }
  }

  /**
   * Get question statistics
   */
  async getQuestionStats() {
    try {
      const questionsSnapshot = await this.db.collection('questions').get();
      const stats = {
        total: 0,
        active: 0,
        pendingReview: 0,
        approved: 0,
        byCategory: {},
        byDifficulty: {},
        byAgeRange: {}
      };

      questionsSnapshot.forEach(doc => {
        const data = doc.data();
        stats.total++;

        if (data.isActive) stats.active++;
        if (data.status === 'pending_review') stats.pendingReview++;
        if (data.status === 'approved') stats.approved++;

        // Category stats
        if (!stats.byCategory[data.category]) {
          stats.byCategory[data.category] = 0;
        }
        stats.byCategory[data.category]++;

        // Difficulty stats
        if (!stats.byDifficulty[data.difficulty]) {
          stats.byDifficulty[data.difficulty] = 0;
        }
        stats.byDifficulty[data.difficulty]++;
      });

      return stats;
    } catch (error) {
      console.error('Error fetching question stats:', error);
      throw new Error('Failed to fetch question statistics');
    }
  }
}

module.exports = new QuestionService();


